"""add interview_guides

Revision ID: 1fb128453421
Revises: 3b40bbce8a00
Create Date: 2026-07-31 19:34:31.177030

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1fb128453421'
down_revision: Union[str, None] = '3b40bbce8a00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interview_guides',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('icon', sa.String(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('introduction', sa.Text(), nullable=True),
    sa.Column('source', sa.Text(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('question_category', sa.String(), nullable=True),
    sa.Column('sections', sa.JSON(), nullable=True),
    sa.Column('checklist', sa.JSON(), nullable=True),
    sa.Column('common_mistakes', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('interview_guides', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_interview_guides_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_interview_guides_slug'), ['slug'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interview_guides', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_interview_guides_slug'))
        batch_op.drop_index(batch_op.f('ix_interview_guides_category'))

    op.drop_table('interview_guides')
    # ### end Alembic commands ###
