"""add time_taken_sec to test_attempts

Revision ID: 3b40bbce8a00
Revises: af72d365741d
Create Date: 2026-07-31 19:22:23.824351

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b40bbce8a00'
down_revision: Union[str, None] = 'af72d365741d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_attempts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time_taken_sec', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_attempts', schema=None) as batch_op:
        batch_op.drop_column('time_taken_sec')

    # ### end Alembic commands ###
