"""Add user profile fields

Revision ID: 7e5e39408ea1
Revises: 1fb128453421
Create Date: 2026-08-12 15:44:15.573667

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e5e39408ea1'
down_revision: Union[str, None] = '1fb128453421'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('headline', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('bio', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('domain', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('linkedin_url', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('github_url', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('github_url')
        batch_op.drop_column('linkedin_url')
        batch_op.drop_column('domain')
        batch_op.drop_column('bio')
        batch_op.drop_column('headline')

    # ### end Alembic commands ###
