"""Add Object Storage fields to Resume

Revision ID: 8e952f83720c
Revises: af6406cf45f3
Create Date: 2026-10-06 01:02:47.644299

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e952f83720c'
down_revision: Union[str, None] = 'af6406cf45f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resumes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('storage_key', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('file_size', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
        batch_op.alter_column('data',
               existing_type=sa.BLOB(),
               nullable=True)
        batch_op.create_unique_constraint('uq_resumes_storage_key', ['storage_key'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resumes', schema=None) as batch_op:
        batch_op.drop_constraint('uq_resumes_storage_key', type_='unique')
        batch_op.alter_column('data',
               existing_type=sa.BLOB(),
               nullable=False)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('file_size')
        batch_op.drop_column('storage_key')

    # ### end Alembic commands ###
