"""make question topic_id nullable

Revision ID: e263a33628a8
Revises: b4c69f83c5c3
Create Date: 2026-09-23 07:29:35.152271

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e263a33628a8'
down_revision: Union[str, None] = 'b4c69f83c5c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.alter_column('topic_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.alter_column('topic_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
